### ISSUE TITLE
Any example colab scripts to fine tune BERT variations for text multi-class classification tasks?

### ISSUE THREAD

**Issue by sjinjala23** [mim-solutions/bert_for_longer_texts#19]
My data has tokens more than 512 and I need to train a bert model (ALBERT base v2) for multiclass text classification task. I can't seem to find any example colab scripts in the repo. Kindly provide with some links or articles.

**Comment by mwachnicki** [comment]
Currently, we only support binary classification. We may add multiclass classification in the future. You can also fork the repo and modify the code by yourself.

**Comment by SalvatoreMirlocca** [comment]
I extended the library to work with multi-class problems. I get great results with a 3-class email classification problem. The longest emails can exceed 10 thousand tokens. I also used a method that frees the memory from unused tensors after each batch processing (I had to use distilBERT because the library is really expensive at the video memory level). I can get great f1 values ​​by only having 581 examples. Unfortunately I'm new to git hub. If you give me some guidance I would be happy to share my work.
