### ISSUE TITLE
A few general questions

### ISSUE THREAD

**Issue by matteobrv** [mim-solutions/bert_for_longer_texts#30]
Hello there! Thank you for this nice project ✨ @mwachnicki @MichalBrzozowski91
I'm really enjoying working through the details! I've just got a few general questions I hope you can help me with.

Let's consider [Devlin's example](https://github.com/google-research/bert/issues/27#issuecomment-435265194) and say we have a 3x6 mini-batch as a result of splitting our input sequence into 3 chunks:
```text
the man went to the store
to the store and bought a
and bought a gallon of milk
```
BELT allows to process the mini-batch in one go and returns a single, pooled probability value as a result.

**Question 1**
As far as the attention mechanism goes, am I right to understand that this is applied separately to each chunk? In other words, the tokens in the first chunk do not attend to the tokens in the second and third one, correct?

**Question 2**
Devlin suggests applying an attention mask to ensure boundary words are not considered twice; in our example `to the store` and `and bought a` in the second and third chunk, respectively. Why don't we simply split the original sentence in a way that the chunks do not overlap? For example:
```text
the man went to the store
and bought a gallon of milk
```
What is the purpose of keeping these overlapping bits if we have to mask them anyway?

**Question 3**
If my considerations in Question 1 are correct and attention is applied separately on each individual chunk, wouldn't it be beneficial to not mask the overlapping boundary words? Intuitively, I'd say this increases the context of each chunk, making them more similar to each other "in the eyes of the model".

Thanks again for the great work!

**Comment by mwachnicki** [comment]
Hello! Thank you for your kind words!

**Question 1**
You are correct. Each chunk is fed to the model as a separate text would normally be, so the attention mechanism is also applied separately.

**Questions 2 and 3**
First of all, you can play with splitting parameters. The details can be found [here](https://mim-solutions.github.io/bert_for_longer_texts/#method).
Setting `stride` equal to `chunk_size` (e.g. 510 tokens) would result in non-overlapping chunks as shown in the example.

We don't apply an attention mask to overlapping tokens. Our intuition is the same as yours - it should be beneficial to have a slightly larger context rather than just split texts in the middle of a sentence. That's why we introduced the said parameters to enable their optimization for each specific case.

If you have any following questions, feel free to reopen.
